AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-s3-to-s3

  Sample SAM Template for aws-s3-to-s3

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  # The Lambda function that copies between buckets and writes the metadata to our DB
  AWSS3FileUpload:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3_to_s3_copy/
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 's3:GetObject'
              Resource: 'arn:aws:s3:::source-bucket-dyslexicat/*'
            - Effect: Allow
              Action:
                - 's3:ListBucket'
              Resource: 'arn:aws:s3:::source-bucket-dyslexicat'
            - Effect: Allow
              Action:
                - 's3:PutObject'
                - 's3:GetObject'
              Resource: 'arn:aws:s3:::target-bucket-dyslexicat/*'
            - Effect: Allow
              Action:
                - 's3:ListBucket'
              Resource: 'arn:aws:s3:::target-bucket-dyslexicat'
      Architectures:
        - x86_64
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref SourceBucket
            Events: s3:ObjectCreated:*

  # Source S3 Bucket
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "source-bucket-dyslexicat"

  # Target S3 Bucket
  TargetBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "target-bucket-dyslexicat"

