AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-s3-to-s3

  Sample SAM Template for aws-s3-to-s3

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Parameters:
  EnvironmentName:
    Description: An environment name that will be used as a suffix for resources
    Type: String
    Default: test
  SourceBucketName:
    Description: The name of the source Bucket
    Type: String
    Default: 'source-bucket-dyslexicat'
  TargetBucketName:
    Description: The name of the target Bucket
    Type: String
    Default: 'target-bucket-dyslexicat'
  DynamoDBTableName:
    Description: The name of the table in DynamoDB that will keep the metadata information
    Type: String
    Default: FileMetadataInfo
  VpcCIDR:
    Description: The IP range (CIDR notation) for this VPC
    Type: String
    Default: 13.37.0.0/16
  PrivateSubnetCIDR:
    Description: The IP range (CIDR notation) for the private subnet
    Type: String
    Default: 13.37.13.0/24

Resources:
  # The VPC for our Lambda function
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-${EnvironmentName}-VPC'

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: !Ref PrivateSubnetCIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Private Subnet (AZ1)

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Private Routes (AZ1)

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet

  NoIngressSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "no-ingress-sg"
      GroupDescription: "Security group with no ingress rule"
      VpcId: !Ref VPC

  # The Lambda function that copies between buckets and writes the metadata to our DB
  AWSS3FileUpload:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3_to_s3_copy/
      Handler: app.lambda_handler
      Runtime: python3.9
      VpcConfig:
        SecurityGroupIds:
          - !Ref NoIngressSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnet
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 's3:Get*'
              Resource: !Sub 'arn:aws:s3:::${SourceBucketName}-${EnvironmentName}/*'
            - Effect: Allow
              Action:
                - 's3:ListBucket'
              Resource: !Sub 'arn:aws:s3:::${SourceBucketName}-${EnvironmentName}'
            - Effect: Allow
              Action:
                - 's3:PutObject'
                - 's3:Get*'
              Resource: !Sub 'arn:aws:s3:::${TargetBucketName}-${EnvironmentName}/*'
            - Effect: Allow
              Action:
                - 's3:ListBucket'
              Resource: !Sub 'arn:aws:s3:::${TargetBucketName}-${EnvironmentName}'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Sid: AccessDynamoTable
              Action:
                - dynamodb:BatchGet*
                - dynamodb:DescribeStream
                - dynamodb:DescribeTable
                - dynamodb:Get*
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:BatchWrite*
                - dynamodb:CreateTable
                - dynamodb:Delete*
                - dynamodb:Update*
                - dynamodb:PutItem
              Resource: !Sub "arn:aws:dynamodb:*:*:table/${DynamoDBTableName}"
      Environment:
        Variables:
          TARGET_BUCKET_NAME: !Sub '${TargetBucketName}-${EnvironmentName}'
          TABLE_NAME: !Ref DynamoDBTableName
      Architectures:
        - x86_64
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref SourceBucket
            Events: s3:ObjectCreated:*

  # Source S3 Bucket
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${SourceBucketName}-${EnvironmentName}'

  # Target S3 Bucket
  TargetBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${TargetBucketName}-${EnvironmentName}'

  # Since our Lambda function is inside a VPC we need an Endpoint to access S3
  S3GatewayEndpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      RouteTableIds:
        - !Ref PrivateRouteTable
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcId: !Ref VPC

  # DynamoDB table
  MetadataTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Ref DynamoDBTableName

  # We need another Gateway Endpoint for our Lambda to access the DynamoDB service
  DynamoGatewayEndpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      RouteTableIds:
        - !Ref PrivateRouteTable
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.dynamodb'
      VpcId: !Ref VPC

